# Generated by Django 4.2.6 on 2023-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_mainimg_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.FloatField(editable=False),
        ),
    ]
