# Generated by Django 4.2.6 on 2023-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_rating_alter_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
