# Generated by Django 4.2.6 on 2023-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_groups_customer_isstaff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
