# Generated by Django 4.2.6 on 2023-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_status_order_iscompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainPrice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
