# Generated by Django 4.2.6 on 2023-11-17 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Invalid username', regex='^[a-zA-Z0-9][a-zA-Z0-9_]*$')]),
        ),
    ]
