# Generated by Django 4.2.6 on 2023-11-17 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Invalid password', regex='^[A-Za-z\\d!@#$%^&*()_+]+$')]),
        ),
    ]
