# Generated by Django 4.2.6 on 2023-11-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_iscomplete_transaction_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transactionId',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
