# Generated by Django 4.2.6 on 2023-12-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_review_product_reviewcount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='username',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptionInfo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescriptionInfo',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
