# Generated by Django 4.2.6 on 2023-12-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_title_review_username_product_descriptioninfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
