# Generated by Django 4.2.6 on 2023-12-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_username_review_title_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='username',
        ),
    ]
