# Generated by Django 4.2.5 on 2023-12-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_review_username_review_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='username',
        ),
    ]
