# Generated by Django 4.2.6 on 2023-12-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_favourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Adresses'},
        ),
    ]
