# Generated by Django 4.2.6 on 2023-12-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_product_newarriwals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeCount',
        ),
    ]
