# Generated by Django 4.2.6 on 2023-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_delete_sizecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subtotalPrice',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
