# Generated by Django 4.2.5 on 2023-12-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_productquantity_delete_productquanity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(editable=False, max_length=16)),
                ('isFreeDelivery', models.BooleanField()),
                ('isDiscount', models.BooleanField()),
                ('discount', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, default=None, editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='couponDiscount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='isDiscountCoupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isFreeDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isUsedCoupon',
            field=models.BooleanField(default=False),
        ),
    ]
