# Generated by Django 4.2.6 on 2023-12-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_coupon_order_coupon_order_coupondiscount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='isDiscount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isDiscountCoupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isFreeDelivery',
        ),
        migrations.AddField(
            model_name='coupon',
            name='isDiscountCoupon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='isFreeDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.coupon'),
        ),
    ]
