# Generated by Django 4.2.6 on 2023-12-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_remove_coupon_isdiscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_staff',
            new_name='isStaff',
        ),
        migrations.AddField(
            model_name='customer',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
