# Generated by Django 4.2.6 on 2023-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='secondName',
            field=models.CharField(max_length=50),
        ),
    ]
