# Generated by Django 4.2.6 on 2023-12-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='secondName',
            new_name='lastName',
        ),
    ]
