# Generated by Django 4.2.6 on 2024-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_rename_secondname_shippingaddress_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileImg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
