# Generated by Django 4.2.6 on 2024-01-07 22:32

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_emailchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainImg',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to_product),
        ),
    ]
