# Generated by Django 4.2.6 on 2024-01-08 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_alter_product_mainimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Invalid password', regex='^[A-Za-z\\d!@#$%^&*()_+]+$')]),
        ),
    ]
